<?php

namespace Database\Seeders;

use App\Enums\Asset\AssetStatus;
use App\Enums\AssetHistory\AssetHistoryAction;
use App\Imports\AssetsImport;
use App\Models\AssetHistory;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;
use App\Models\Asset;

use Carbon\Carbon;

class AssetSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        AssetHistory::truncate();
        Asset::truncate();

         $filePath = storage_path('app/import_data.xlsx');

    // Convertir el Excel a un Array
    $rows = Excel::toArray(new AssetsImport, $filePath);

    // El primer índice [0] es la primera hoja del Excel
    foreach ($rows[0] as $row) {
        User::create([
            'name'  => $row[0],
            'email' => $row[1],
            'password' => bcrypt('password123'),
        ]);

        Asset::insert([
            ...$this->getLimaTechnicalAssets(),
            // ...$this->getProvincialTechnicalAssets(),

        ]);



        AssetHistory::insert(
            Asset::get()->map(fn($asset) => [
                'action' => AssetHistoryAction::CREATED->value,
                'description' => 'Equipo registrado en el sistema',
                'asset_id' => $asset->id,
                'performed_by' => 137,
                'performed_at' => Carbon::now(),
            ])->toArray()
        );

        Schema::enableForeignKeyConstraints();
    }


    private function getLimaTechnicalAssets()
    {
        return [
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'Lenovo',
                'model' => 'V15 ITL',
                'color' => null,
                'serial_number' => 'PF3T5WH9',
                'processor' => 'I5-1135G7',
                'ram' => '8GB',
                'storage' => '256GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'HP',
                'model' => 'EliteBook 820 G3',
                'color' => null,
                'serial_number' => '5CG77134X0K',
                'processor' => 'I5-6300U',
                'ram' => '8GB',
                'storage' => '256GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'Lenovo',
                'model' => 'V15 ITL',
                'color' => null,
                'serial_number' => 'PF3T7GPD',
                'processor' => 'I5-1135G7',
                'ram' => '12GB',
                'storage' => '512GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ], //
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'LENOVO',
                'model' => 'v15 G2 ITL S',
                'color' => null,
                'serial_number' => 'PF3T3KAC',
                'processor' => null,
                'ram' => null,
                'storage' => null,
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'ASUS',
                'model' => 'UX310U',
                'color' => null,
                'serial_number' => 'NOCV1646MB0035025',
                'processor' => 'i5-7200U',
                'ram' => '12GB',
                'storage' => '500GB-HDD',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'HP',
                'model' => 'EliteBook 820 G3',
                'color' => null,
                'serial_number' => '5CG8084NYL',
                'processor' => 'i5-6300U',
                'ram' => '8GB',
                'storage' => '256GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'Lenovo',
                'model' => 'IdeaPad 330-10IGL',
                'color' => null,
                'serial_number' => 'YX033CGE',
                'processor' => 'CELERON(R) N4020',
                'ram' => '8GB',
                'storage' => '116GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'HP',
                'model' => 'EliteBook 820 G3',
                'color' => null,
                'serial_number' => '5CG63931ZV',
                'processor' => 'i5-6300U',
                'ram' => '8GB',
                'storage' => '256GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'DELL',
                'model' => 'Latitude 5400',
                'color' => 'Negro',
                'serial_number' => '2W6GP13',
                'processor' => 'i5-8265U',
                'ram' => '16GB',
                'storage' => '512GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'Lenovo',
                'model' => 'Latitude 5400',
                'color' => null,
                'serial_number' => null,
                'processor' => 'I7-10510U',
                'ram' => '16GB',
                'storage' => '512GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'Lenovo',
                'model' => 'IdeaPad 3 ITL 6',
                'color' => 'Negro',
                'serial_number' => 'PF9XB2915172',
                'processor' => 'i5-1155G7',
                'ram' => '8GB',
                'storage' => '256GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'Lenovo',
                'model' => '81M9',
                'color' => null,
                'serial_number' => null,
                'processor' => null,
                'ram' => null,
                'storage' => null,
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'DELL',
                'model' => 'LATITUDE 7290',
                'color' => null,
                'serial_number' => 'BM8VMV2',
                'processor' => 'I5-8250U',
                'ram' => '16GB',
                'storage' => '512GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'DELL',
                'model' => 'Inspiron 15',
                'color' => null,
                'serial_number' => null,
                'processor' => null,
                'ram' => null,
                'storage' => null,
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'Lenovo',
                'model' => '83A1',
                'color' => null,
                'serial_number' => null,
                'processor' => null,
                'ram' => null,
                'storage' => null,
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'Lenovo',
                'model' => 'IdeaPad Slim 3 15AH8',
                'color' => null,
                'serial_number' => 'PF573SPY',
                'processor' => 'INTEL I5 1245OH',
                'ram' => '8GB',
                'storage' => '512GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'Lenovo',
                'model' => '83A1',
                'color' => null,
                'serial_number' => null,
                'processor' => null,
                'ram' => null,
                'storage' => null,
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'DELL',
                'model' => 'LATITUDE 7290',
                'color' => null,
                'serial_number' => '1M6RMV2',
                'processor' => 'I5-8250U',
                'ram' => '8GB',
                'storage' => '512GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'LENOVO',
                'model' => 'IDEAPAD 3 ITL 6',
                'color' => null,
                'serial_number' => 'PF40TNDA',
                'processor' => 'I5-1155G7',
                'ram' => '8GB',
                'storage' => '256GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'LENOVO',
                'model' => 'LATITUDE 5400',
                'color' => null,
                'serial_number' => '9Q37ZY2',
                'processor' => 'I5-8265U',
                'ram' => '16GB',
                'storage' => '512GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'DELL',
                'model' => 'LATITUDE 7290',
                'color' => null,
                'serial_number' => '501RMV2',
                'processor' => 'I5-8250U',
                'ram' => '8GB',
                'storage' => '512GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'DELL',
                'model' => 'LATITUDE 7300',
                'color' => null,
                'serial_number' => '7RTYY2',
                'processor' => 'i5-8265U',
                'ram' => '8GB',
                'storage' => '477GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'DELL',
                'model' => 'LATITUDE 7290',
                'color' => null,
                'serial_number' => '4X0RMV2',
                'processor' => 'I5-8250U',
                'ram' => '16GB',
                'storage' => '512GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'HP',
                'model' => 'ELITE BOOK 820 G3',
                'color' => null,
                'serial_number' => '5CG63930PS',
                'processor' => 'I5-6300U',
                'ram' => '8GB',
                'storage' => '256GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'HP',
                'model' => '250 G6',
                'color' => null,
                'serial_number' => 'CND91352VJ',
                'processor' => 'I5-7200U',
                'ram' => '16GB',
                'storage' => '256GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],


            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'HP',
                'model' => 'ELITE BOOK 820 G3',
                'color' => null,
                'serial_number' => '5CG639355C',
                'processor' => 'I5-6300U',
                'ram' => '8GB',
                'storage' => '256GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],


            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'Lenovo',
                'model' => 'T490',
                'color' => null,
                'serial_number' => '2CDVC2',
                'processor' => 'I7-10510U',
                'ram' => '16GB',
                'storage' => '512GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'HP',
                'model' => 'ELITE BOOK 820 G3',
                'color' => null,
                'serial_number' => '5CG6266ZJW',
                'processor' => 'I5-6300U',
                'ram' => '8GB',
                'storage' => '256GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'LENOVO',
                'model' => 'IDEAPAD 3 ITL 6',
                'color' => null,
                'serial_number' => 'PF40WAKD',
                'processor' => 'I5-1155G7',
                'ram' => '8GB',
                'storage' => '256GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'HP',
                'model' => 'ELITE BOOK 820 G3',
                'color' => null,
                'serial_number' => '5CG6393B5Z',
                'processor' => 'I5-6300U',
                'ram' => '8GB',
                'storage' => '256GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'DELL',
                'model' => 'LATITUDE 5400',
                'color' => null,
                'serial_number' => 'FM1FP13',
                'processor' => 'I5-8265U',
                'ram' => '16GB',
                'storage' => '512GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'HP',
                'model' => 'ELITE BOOK 820 G3',
                'color' => null,
                'serial_number' => '5CG8084P5N',
                'processor' => 'I5-6300U',
                'ram' => '8GB',
                'storage' => '256GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'HP',
                'model' => 'ELITE BOOK 820 G3',
                'color' => null,
                'serial_number' => '5CG6393CT6',
                'processor' => 'I5-6300U',
                'ram' => '8GB',
                'storage' => '256GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'DELL',
                'model' => 'P25T',
                'color' => null,
                'serial_number' => '77P6LJ2',
                'processor' => 'CELERON N4020',
                'ram' => '8GB',
                'storage' => '128GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'HP',
                'model' => 'ELITE BOOK 820 G3',
                'color' => null,
                'serial_number' => '5CG6393H46',
                'processor' => 'I5-6300U',
                'ram' => '8GB',
                'storage' => '256GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'HP',
                'model' => '250 G6',
                'color' => null,
                'serial_number' => 'CND9135ZR4',
                'processor' => 'I3-7020U',
                'ram' => '16GB',
                'storage' => '240GB SSD',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'Lenovo',
                'model' => 'V15 G4 IAH',
                'color' => null,
                'serial_number' => 'PF4TBX9H',
                'processor' => 'I5-12500H',
                'ram' => '8GB',
                'storage' => '512GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],


            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'HP',
                'model' => 'ELITE BOOK 820 G3',
                'color' => null,
                'serial_number' => '5CG639227L',
                'processor' => 'I5-6300U',
                'ram' => '8GB',
                'storage' => '256GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],


            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'HP',
                'model' => 'ELITE BOOK 820 G3',
                'color' => null,
                'serial_number' => '5CG63933MH',
                'processor' => 'I5-6300U',
                'ram' => '8GB',
                'storage' => '256GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],



            // ---------------- TABLETS ----------------
            [
                'name' => 'TABLET TECLADO',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'LENOVO',
                'model' => 'D330-10IGL',
                'color' => null,
                'serial_number' => 'YX033D5H',
                'processor' => 'CELERON N4020',
                'ram' => '8GB',
                'storage' => '128GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 3,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'TABLET TECLADO',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'Lenovo',
                'model' => 'D330-10IGL',
                'color' => null,
                'serial_number' => 'YX033TH2',
                'processor' => 'N4020',
                'ram' => '8GB',
                'storage' => '128GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 3,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
    }

    private function getProvincialTechnicalAssets(
    ) {
        return [
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'HP',
                'model' => 'ELITE BOOK 820 G3',
                'color' => null,
                'serial_number' => '5CG5266ZMT',
                'processor' => 'I5-6300U',
                'ram' => '8GB',
                'storage' => '256GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'ASUS',
                'model' => 'X407U',
                'color' => null,
                'serial_number' => 'K6N0GR05126724F',
                'processor' => 'I3-7020',
                'ram' => '8GB',
                'storage' => '500GB-HDD',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'HP',
                'model' => 'ELITE BOOK 820 G3',
                'color' => null,
                'serial_number' => '5CG8084NXT',
                'processor' => 'I5-6300U',
                'ram' => '8GB',
                'storage' => '256GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'LENOVO',
                'model' => 'E41-50',
                'color' => null,
                'serial_number' => 'MP22KKT9',
                'processor' => null,
                'ram' => null,
                'storage' => null,
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'HP',
                'model' => 'ELITE BOOK 820 G3',
                'color' => null,
                'serial_number' => 'SCG6393941',
                'processor' => 'I5-6300U',
                'ram' => '8GB',
                'storage' => '256GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'DELL',
                'model' => 'LATITUDE 7290',
                'color' => null,
                'serial_number' => 'F1LKMV2',
                'processor' => 'I5-8250U',
                'ram' => '16GB',
                'storage' => '512GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'LENOVO',
                'model' => 'Thinkpad T490',
                'color' => null,
                'serial_number' => 'PF-2CDY58',
                'processor' => null,
                'ram' => null,
                'storage' => null,
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'ASUS',
                'model' => 'V15 G4 IRU',
                'color' => null,
                'serial_number' => 'K6NOGR05323024H',
                'processor' => null,
                'ram' => null,
                'storage' => null,
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'Lenovo',
                'model' => '300e 2nd Gen',
                'color' => null,
                'serial_number' => null,
                'processor' => null,
                'ram' => null,
                'storage' => null,
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'ASUS',
                'model' => 'X407U',
                'color' => null,
                'serial_number' => 'K6N0GR05321424E',
                'processor' => 'I3-7020',
                'ram' => '8GB',
                'storage' => '500GB-HDD',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'LENOVO',
                'model' => null,
                'color' => null,
                'serial_number' => '0CZMCK',
                'processor' => 'I5-6Ta',
                'ram' => '8GB',
                'storage' => '256GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'DELL',
                'model' => 'LATITUDE 5400',
                'color' => null,
                'serial_number' => '1QPGP13',
                'processor' => 'I5-8265U',
                'ram' => '16GB',
                'storage' => '512GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'HP',
                'model' => 'ELITE BOOK 820 G3',
                'color' => null,
                'serial_number' => '5CG6266Z45',
                'processor' => 'I5-6300U',
                'ram' => '8GB',
                'storage' => '256GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'HP',
                'model' => 'ELITE BOOK 820 G3',
                'color' => null,
                'serial_number' => '5CG6266ZPT',
                'processor' => 'I5-6300U',
                'ram' => '8GB',
                'storage' => '256GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'LENOVO',
                'model' => 'E41-50',
                'color' => null,
                'serial_number' => 'MP22KT80',
                'processor' => 'I3-1135G5',
                'ram' => '8GB',
                'storage' => '512GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'HP',
                'model' => '250 G8',
                'color' => null,
                'serial_number' => 'CND2223SYZ',
                'processor' => 'I5-1135G7',
                'ram' => '8GB',
                'storage' => '256GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'HP',
                'model' => 'ELITE BOOK 820G3',
                'color' => null,
                'serial_number' => 'SCG6393D62',
                'processor' => 'I5-6300U',
                'ram' => '8GB',
                'storage' => '256GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'ASUS',
                'model' => 'X407U',
                'color' => null,
                'serial_number' => 'K6N0GR05312024F',
                'processor' => 'I3-7020',
                'ram' => '8GB',
                'storage' => '500GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'ASUS',
                'model' => 'X407U',
                'color' => null,
                'serial_number' => 'K6N0GR05183124E',
                'processor' => 'I5-8250U',
                'ram' => '8GB',
                'storage' => '256GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'HP',
                'model' => 'ELITE BOOK 820 G3',
                'color' => null,
                'serial_number' => '5CG6266ZQ2',
                'processor' => 'I5-6300U',
                'ram' => '8GB',
                'storage' => '256GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'DELL',
                'model' => 'LATITUDE 5400',
                'color' => null,
                'serial_number' => 'BW17ZY2',
                'processor' => 'I5-8265U',
                'ram' => '16GB',
                'storage' => '512GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'DELL',
                'model' => 'LATITUDE 7290',
                'color' => null,
                'serial_number' => 'GY9LMV2',
                'processor' => 'I5-8250U',
                'ram' => '8GB',
                'storage' => '512GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'HP',
                'model' => 'ELITE BOOK 820 G3',
                'color' => null,
                'serial_number' => '5CG63934B9',
                'processor' => 'I5-6300U',
                'ram' => '8GB',
                'storage' => '256GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'ASUS',
                'model' => 'X407U',
                'color' => null,
                'serial_number' => 'K6N0GR05173624E',
                'processor' => 'I5-8250U',
                'ram' => '8GB',
                'storage' => '256GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'DELL',
                'model' => 'LATITUDE 7290',
                'color' => null,
                'serial_number' => '831RMV2',
                'processor' => 'I5-8250U',
                'ram' => '8GB',
                'storage' => '512GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'HP',
                'model' => 'ELITE BOOK 820 G3',
                'color' => null,
                'serial_number' => '5CG63939WS',
                'processor' => 'I5-6300U',
                'ram' => '8GB',
                'storage' => '256GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'DELL',
                'model' => 'LATITUDE 7290',
                'color' => null,
                'serial_number' => '2T0RMV2',
                'processor' => 'I5-8250U',
                'ram' => '8GB',
                'storage' => '512GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'HP',
                'model' => 'ELITE BOOK 820 G3',
                'color' => null,
                'serial_number' => '5CG6266Z1P',
                'processor' => 'I5-6300U',
                'ram' => '8GB',
                'storage' => '256GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'HP',
                'model' => 'ELITE BOOK 820 G3',
                'color' => null,
                'serial_number' => '5CG8084NY4',
                'processor' => 'I5-6300U',
                'ram' => '8GB',
                'storage' => '256GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'HP',
                'model' => 'ELITE BOOK 820 G3',
                'color' => null,
                'serial_number' => '5CG6393GL3',
                'processor' => 'I5-6300U',
                'ram' => '8GB',
                'storage' => '256GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'DELL',
                'model' => 'LATITUDE 7300',
                'color' => null,
                'serial_number' => '1DKTYY2',
                'processor' => 'I5-8265U',
                'ram' => '8GB',
                'storage' => '512GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'HP',
                'model' => 'ELITE BOOK 820 G3',
                'color' => null,
                'serial_number' => '5CG63931BZ',
                'processor' => 'I5-6300U',
                'ram' => '8GB',
                'storage' => '256GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'HP',
                'model' => '245 G5',
                'color' => null,
                'serial_number' => '5CG7134X2Q',
                'processor' => 'I5-1135G7',
                'ram' => '8GB',
                'storage' => '256GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'HP',
                'model' => 'ELITE BOOK 820 G3',
                'color' => null,
                'serial_number' => '5CG6266ZM0',
                'processor' => 'I5-6300U',
                'ram' => '8GB',
                'storage' => '256GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'HP',
                'model' => 'ELITE BOOK 820 G3',
                'color' => null,
                'serial_number' => '5CG6400PZW',
                'processor' => 'I5-6300U',
                'ram' => '8GB',
                'storage' => '256GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'HP',
                'model' => 'ELITE BOOK 820 G3',
                'color' => null,
                'serial_number' => '5CG63935CD',
                'processor' => 'I5-6300U',
                'ram' => '8GB',
                'storage' => '256GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'LENOVO',
                'model' => '82KB',
                'color' => null,
                'serial_number' => 'PF3P5LD1',
                'processor' => 'i5-1135G7',
                'ram' => '8GB',
                'storage' => '238GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'DELL',
                'model' => 'INSPIRON 14 7437',
                'color' => null,
                'serial_number' => 'CQXS712',
                'processor' => 'I5-4210U',
                'ram' => '6GB',
                'storage' => '480GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ---------------- TABLET PROVINCIALES ----------------
            [
                'name' => 'TABLET TECLADO',
                'status' => AssetStatus::AVAILABLE->value,
                'brand' => 'LENOVO',
                'model' => 'D330-10IGL',
                'color' => null,
                'serial_number' => 'YX033D0Q',
                'processor' => 'N4020',
                'ram' => '8GB',
                'storage' => '128GB',
                'purchase_date' => now()->subYears(2),
                'warranty_expiration' => now()->addYear(),
                'type_id' => 1,
                'is_new' => false,
                'invoice_path' => null,
                'phone' => null,
                'imei' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];
    }
}
