import { Department } from "./department.interace";

export interface User {
    staff_id: number;
    full_name: string;
    dept_id: number;
    role_id: number;
    username: string;
    firstname?: string;
    lastname?: string;
    passwd?: string;
    password?: string;
    backend?: string;
    email?: string;
    phone: string;
    phone_ext?: string;
    mobile: string;
    signature: string;
    lang?: string;
    timezone?: string;
    locale?: string;
    notes?: string;
    isactive: number;
    isadmin: number;
    isvisible: number;
    onvacation: number;
    assigned_only: number;
    show_assigned_tickets: number;
    change_passwd: number;
    max_page_size: number;
    auto_refresh_rate: number;
    default_signature_type: 'none' | 'mine' | 'dept';
    default_paper_size: 'Letter' | 'Legal' | 'Ledger' | 'A4' | 'A3';
    extra?: string;
    permissions?: string;
    created: Date;
    lastlogin?: Date;
    passwdreset?: Date;
    updated: Date;
    dni?: string;
    direccion?: string;
    id_departamento?: number;
    id_provincia?: number;
    id_distrito?: number;
    zona_tecnico?: string;
    id_empresa?: number;
    fecha_ingreso?: Date;
    id_cargo?: number;
    id_area?: number;
    activo: number;
    department?: Department;
}
